config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/contact" => "pages#contact"
  get "/about" => "pages#about"
  get "/plantcards/:id/download_pdf", to: "plantcards#download_pdf", as: :plantcards

  resources :plants, only: [:index, :show]
  resources :plantcards, only: [:show, :download_pdf]
  resources :symptoms, only: [:index, :show]
  resources :tratamentos, only: [:index, :show]
  resources :tipos, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :plantcard

  has_one_attached :file_content
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :plantcards
  belongs_to :tipo
end

app/models/plantcard.rb
class Plantcard < ApplicationRecord
  belongs_to :plant
  has_one :content

  # def download
  #   UserMailer.file_loading(self).deliver_now
  # end

  def download_pdf(plantcard: "")
    @plantcard = Plantcard.find(params[:id])
    send_file("#{Rails.root}/db/fixtures/plant_contents/plant_#{@plantcard}.pdf",
      filename: "plant_#{@plantcard}.pdf",
      type: "application/pdf"
    )
  end

  # private

  # def set_plantcard
  #   @plantcard = Plantcard.find(params[:id])
  # end

  # def plantcard_params
  #   params.require(:plantcard).permit(:plant_id, :title)
  # end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
  has_many :plants
end

app/models/tratamento.rb
class Tratamento < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :send_welcome_email
  after_create :send_loading

  private

  def redirect_to_plantcard_show
    redirect_to 'plantcard/id'
  end

  def send_loading
    UserMailer.file_loading(self).deliver_now
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  require 'open-uri'
  require 'nokogiri'

  def home
    @plants = Plant.all
    @symptoms = Symptom.all
    @tipos = Tipo.all
  end

  def contact
    @tel = "0635158132"
  end

  def about
    @text = "Este site foi inspirado da obra de Harri Lorenzi e F.J.
    Abreu Matos: 'Plantas Medicinais no Brasil, Nativas e Exóticas, 2nda edição.'
    Foi um privilegio de reunir todas as informações preciosas deste livro
    e uma trabalho feliz de criar este conteúdo a disposicao do grande publico.
    Agradeço ao conhecimento que me foi devolvido atraves deste livro e parabenizo a obra mais uma vez.
    Anthony, WebDesigner - Lite Services"
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!, only: [:download_pdf]
  # before_action :set_plant, only: [:show]
  # before_action :set_user, only: [:download_pdf]
  require 'open-uri'
  require 'nokogiri'
  require 'csv'

  def index
    @plants = Plant.all
    @symptoms = Symptom.all
    @tipos = Tipo.all
  end

  def show
    @user  = current_user
    @tipos = Tipo.all
    @plant = Plant.find(params[:id])
    @seed  = @plant.tipo_id
    @result = @tipos.where(id: @seed)
    @all_plants = Plant.all
    @symptoms   = Symptom.all
    @plant_number = @plant.number
    @a = []
    @sympts = @symptoms.each do |sympt|
      @a << sympt
    end
    @index = @sympts.each do |sympt|
      sympt.nom
      sympt.plants.split
    end
    @recipes      = @symptoms.where(plants: "#{@a.split}")
    @number_plant = Symptom.where(plants: @plant_number)
  end

  def plant_infos
    @plant = Plant.find(params[:id])
    @plant_info_doc = "./plants/plant_infos.html.erb"
    @serialized_doc = File.read(@plant_info_doc)
    @document = Document.find(params[:id])
    send_data @document.file.read, filename: @document.name
  end

  private

  def set_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
    params.require(:plant).permit(:number, :nom_scientifique)
  end

  # def set_user
  #   @user = User.find(params[:id])
  # end

  # # Only allow a list of trusted parameters through.
  # def user_params
  #   params.require(:user).permit(:name, :email, :login)
  # end
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  before_action :set_symptom, only: [:show]
  require 'open-uri'
  require 'nokogiri'
  require "csv"

  def index
    @symptoms = Symptom.all
  end

  def show
    @plant_index = Plant.all
    @symptom  = Symptom.find(params[:id])
    @healings = @symptom.plants.split
    @plantes  = @healings
    @number_plant = Plant.where(number: @plantes)
  end

  private

  def set_symptom
    @symptom = Symptom.find(params[:id])
  end

  def symptom_params
    params.require(:symptom).permit(:name, :plants)
  end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController

  def index
    @especies = Tipo.all
    @plants  = Plant.all
  end

  def show
    @especie = Tipo.find(params[:id])
    @these_plants = Plant.where(tipo_id: @especie)
  end

  private

  def set_tipo
    @tipo = Tipo.find(params[:id])
  end

  def tipo_params
    params.require(:tipo).permit(:especie)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @plants = Plant.all
    @user = User.new(user_params)
    if @user.save
      # UserMailer.with(user: @user).welcome_email.deliver_now
      UserMailer.welcome_email(@plantcard).deliver_now
      redirect_to plantcard_path(@plant.id), notice: "User was successfully created."
      # format.json { render :show, status: :created, location: @user }
    else
      render :new
      # , status: :unprocessable_entity
      # format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plantcards_helper.rb
module PlantcardsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
# @user_signed_in?
# # => true / false

# current_user
# # => User instance / nil
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/tratamentos_helper.rb
module TratamentosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/plants/form.html.erb
<%= simple_form_for(@user, :url => users_trial_signup_submit_path(@user)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.fields_for :plants do |u| %>
          <%= u.text_field :name, placeholder: "What's your name'",
                      required: true,
                      input_html: { autocomplete: "name" } %>
          <%= u.text_field :email,
                      required: true,
                      autofocus: true,
                      input_html: { autocomplete: "email" }%>
        </div>
        <% end %>
        <div class="form-actions">
          <%= f.button :submit, 'Download PDF', plants_download_pdf_url %>
        </div>
      <% end %>

app/views/plants/plant_infos.html.erb
<%= @plant.nom_scientifique %>
<%= link_to "Download", File.basename(f.stored_file.url) %>

app/views/plants/show.html.erb
<div class="container-plant">
  <div class="container-in-block">
  <h1><%= @plant_number %> - <%= @plant.nom_scientifique %></h1>
  <h4>Especie</h4>
  <p><%= @result[0].especie %></p>
  <h4>Nomes Populares</h4>
  <p><%= @plant.noms_populaires %></p>
    <h2>Sintomas</h2>
    <div class="sintomas-columns">
      <% @index.each do |i| %>
        <% if i.plants.split.include?(@plant_number) == true %>
        <%= link_to i.nom, symptom_path(i.id) %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="container-form">
      <h3>Téléchargez la fiche de cette plante</h3>
    <form>
    <div class="form-group">
      <label for="exampleInputPassword1">Nome</label>
      <input type="nom" class="form-control" id="exampleInputNom1" placeholder="Nom">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Email</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      <br><small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
      <% if user_signed_in? %>
        <button type="submit" class="btn btn-primary">
          <%= link_to 'See more', plantcard_path(@plant.id) %>
        </button>
        <% else %>
        <button type="submit" class="btn btn-primary">
          <%= link_to 'Acesso ao nosso guia das plantas medicinais', new_user_registration_path %>
        </button>
      <% end %>
    </form>
  </div>
</div>

app/views/symptoms/show.html.erb
<h1><%= @symptom.nom %></h1>
<p>
<!-- <% @healings.each do |healing| %> -->
<!--   <%= healing %> -->
<!--   <% end %> -->
</p>
<h2>Para tratar esta doença, utilizar:</h2>
<% @number_plant.each do |plant| %>
<p><%= plant.number %> - <%= link_to plant.nom_scientifique, plant_path(plant) %></p>
<% end %>

app/views/tipos/index.html.erb
<div class='container-home'>
  <h1>Especies</h1>
  <% @especies.each do |especie| %>
  <a><%= link_to especie.especie, tipo_path(especie) %>(<%= @plants.where(tipo_id: especie.id).count %>) - <a>
  <% end %>
</div>

app/views/tipos/show.html.erb
<div class="container-home">
  <h1><%= @especie.especie %></h1>
  <div class="container-cards">
    <% @these_plants.each do |this_plant| %>
    <div class="cards">
      <%= link_to this_plant.nom_scientifique, plant_path(this_plant) %>
    </div>
    <% end %>
  </div>
<h1><%= link_to 'Back to Especies Index', tipos_path %></h1>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :login %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>