config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/contact" => "pages#contact"
  get "/about" => "pages#about"
  get "/plantcards/:id/download_pdf", to: "plantcards#download_pdf", as: :plantcards

  resources :plants, only: [:index, :show]
  resources :plantcards, only: [:show, :download_pdf]
  resources :symptoms, only: [:index, :show]
  resources :tratamentos, only: [:index, :show]
  resources :tipos, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :plantcard

  has_one_attached :file_content
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :plantcards
  belongs_to :tipo
end

app/models/plantcard.rb
class Plantcard < ApplicationRecord
  belongs_to :plant
  has_one :content

  # def download
  #   UserMailer.file_loading(self).deliver_now
  # end

  def download_pdf(plantcard: "")
    @plantcard = Plantcard.find(params[:id])
    send_file("#{Rails.root}/db/fixtures/plant_contents/plant_#{@plantcard}.pdf",
      filename: "plant_#{@plantcard}.pdf",
      type: "application/pdf"
    )
  end

  # private

  # def set_plantcard
  #   @plantcard = Plantcard.find(params[:id])
  # end

  # def plantcard_params
  #   params.require(:plantcard).permit(:plant_id, :title)
  # end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
  has_many :plants
end

app/models/tratamento.rb
class Tratamento < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :send_welcome_email
  after_create :send_loading

  private

  def redirect_to_plantcard_show
    redirect_to 'plantcard/id'
  end

  def send_loading
    UserMailer.file_loading(self).deliver_now
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  require 'open-uri'
  require 'nokogiri'

  def home
    @plants = Plant.all
    @symptoms = Symptom.all
    @tipos = Tipo.all
  end

  def contact
    @tel = "0635158132"
  end

  def about
    @text = "Este site foi inspirado da obra de Harri Lorenzi e F.J.
    Abreu Matos: 'Plantas Medicinais no Brasil, Nativas e Exóticas, 2nda edição.'
    Foi um privilegio de reunir todas as informações preciosas deste livro
    e uma trabalho feliz de criar este conteúdo a disposicao do grande publico.
    Agradeço ao conhecimento que me foi devolvido atraves deste livro e parabenizo a obra mais uma vez.
    Anthony, WebDesigner - Lite Services"
  end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController

  def index
    @especies = Tipo.all
    @plants  = Plant.all
  end

  def show
    @especie = Tipo.find(params[:id])
    @these_plants = Plant.where(tipo_id: @especie)
  end

  private

  def set_tipo
    @tipo = Tipo.find(params[:id])
  end

  def tipo_params
    params.require(:tipo).permit(:especie)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @plants = Plant.all
    @user = User.new(user_params)
    if @user.save
      # UserMailer.with(user: @user).welcome_email.deliver_now
      UserMailer.welcome_email(@plantcard).deliver_now
      redirect_to plantcard_path(@plant.id), notice: "User was successfully created."
      # format.json { render :show, status: :created, location: @user }
    else
      render :new
      # , status: :unprocessable_entity
      # format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plantcards_helper.rb
module PlantcardsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
# @user_signed_in?
# # => true / false

# current_user
# # => User instance / nil
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/tratamentos_helper.rb
module TratamentosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brasilmedicinalplants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= link_to "Home", root_path %>
    <%= link_to "Sintomas", symptoms_path %>
    <%= link_to "Plantas", plants_path %>
    <%= link_to "Especies", tipos_path %>
    <%= link_to "Usos", tratamentos_path %>
      <% if user_signed_in? %>
      <p><%= "You are online" %></p>
      <% else %>
      <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= link_to "Home", root_path %>
    <%= link_to "Usos", tratamentos_path %>
    <%= link_to "Contact", contact_url %>
    <%= link_to "About", about_url %>
    <p>
      A SABER:
      Não use plantas sem saber como: faça o download do nosso guia de
      plantas medicinais do Brasil.
      Tome cuidado para descobrir qual parte da planta será usada,
      e descubra as receitas em nosso guia de plantas medicinais do Brasil.
    </p>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container-home">
<%= @text %>
</div>

app/views/pages/contact.html.erb
<div class="container-home">
  <%= @tel %>
</div>

app/views/pages/home.html.erb
<p>
  <%= @tipos.count  %> especies
  <%= @plants.count %> plantas
  <%= @symptoms.count %> sintomas
</p>
<a>
Chaque plante a des vertus qui peuvent calmer, guérir et
soigner de nombreux symptômes. Ce site recense <%= @tipos.count  %> espèces des <%= @plants.count %>
plantes médicinales du Brésil, agissant sur <%= @symptoms.count %> symptômes.
</a>
<div class='container-home'>
  <h1>Especies</h1>
  <% @tipos.each do |especie| %>
  <%= link_to especie.especie, tipo_path(especie) %>
  <% end %>
</div>
<div class='container-home'>
  <h1>Plantas</h1>
  <% @plants.each do |plant| %>
  <%= link_to plant.nom_scientifique, plant_path(plant) %>
  <% end %>
</div>
<div class='container-home'>
 <h1>Sintomas</h1>
  <% @symptoms.each do |symptom| %>
  <%= link_to symptom.nom, symptom_path(symptom) %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
<h1>PLANTAS MEDICINAIS DO BRASIL</h1>
<h2>Nativas e Exóticas</h2>
</div>